FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend /app/backend
ENV PYTHONPATH=/app/backend:/app
WORKDIR /app/backend
CMD ["celery", "-A", "app.workers.celery_app.celery_app", "beat", "--loglevel=INFO"]
