apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: biomedical-ai
spec:
  replicas: 1
  selector:
    matchLabels: { app: qdrant }
  template:
    metadata:
      labels: { app: qdrant }
    spec:
      containers:
        - name: qdrant
          image: qdrant:latest
          ports:
            - containerPort: 8080
